# Generated by Django 6.1.1 on 2026-09-16 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number', models.PositiveSmallIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='semesters', to='academics.academicyear')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='semesters', to='academics.faculty')),
            ],
            options={
                'ordering': ['academic_year', 'faculty', 'number'],
                'constraints': [models.UniqueConstraint(fields=('academic_year', 'faculty', 'number'), name='unique_semester_per_year_faculty')],
            },
        ),
    ]
