# Generated by Django 6.1.1 on 2026-09-16 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_semester'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ['name']},
        ),
        migrations.RemoveConstraint(
            model_name='semester',
            name='unique_semester_per_year_faculty',
        ),
        migrations.AlterField(
            model_name='semester',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.RemoveField(
            model_name='semester',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='number',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='updated_at',
        ),
    ]
