# Generated by Django 6.1.1 on 2026-09-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicyear',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='faculty',
            name='faculty_id',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True, unique=True),
        ),
    ]
