# Generated by Django 6.1.1 on 2026-09-17 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_alter_academicyear_options_alter_faculty_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(editable=False, max_length=30, unique=True),
        ),
    ]
